version: '3.8'

services:
  hr-assistant:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: hr-assistant-container
    ports:
      - "${HR_PORT:-8501}:8501"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY:-}
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=false
    volumes:
      # Mount API key file if exists
      - ./api.txt:/app/api.txt
      # Mount for logs and data persistence
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network
    command: ["streamlit", "run", "hr_assistant_enhanced.py", "--server.port=8501", "--server.address=0.0.0.0", "--server.headless=true", "--server.enableCORS=false"]

  # Jenkins CI/CD Server
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins-container
    user: root
    privileged: true
    ports:
      - "${JENKINS_PORT:-8888}:8080"  # Jenkins web interface - changed from 8080 to 8888
      - "50000:50000"  # Jenkins agents
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins-casc.yaml:/var/jenkins_home/casc_configs/jenkins.yaml
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - JENKINS_OPTS=--prefix=/jenkins
    networks:
      - app-network
    restart: unless-stopped

  # Nginx service for production
  nginx:
    image: nginx:alpine
    container_name: nginx-container
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - hr-assistant
      - jenkins
    networks:
      - app-network
    restart: unless-stopped
    profiles:
      - production

networks:
  app-network:
    driver: bridge

volumes:
  jenkins_home:
    driver: local
  logs:
    driver: local
  data:
    driver: local
